import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "../components/theme-provider";
import Navbar from "@/src/components/navbar"
import HeaderLogo from "../components/header-logo";
import { CartProvider } from "@/lib/contexts/cartContext";


const interFont = Inter({
  subsets: ["latin"]
})


export const metadata: Metadata = {
  title: "Mayhem Records",
  description: "Generated by create next app",
};


export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {

  return (
    <html lang="pt-br" className={interFont.className} suppressHydrationWarning>
      <body>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          <HeaderLogo/>
          <CartProvider>
            {children}
          </CartProvider>
          <Navbar/>
        </ThemeProvider>
      </body>
    </html>
  );
}
