import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "../components/theme-provider";
import Navbar from "../components/navbar";
import HeaderLogo from "../components/header-logo";
import { CartProvider } from "@/lib/contexts/cartContext";
import { FavoritesProvider } from "@/lib/contexts/favoritesContext";
import { SearchHistoryProvider } from "@/lib/contexts/searchHistoryContext";
import { SpeedInsights } from "@vercel/speed-insights/next"


const interFont = Inter({
  subsets: ["latin"]
})


export const metadata: Metadata = {
  title: "Mayhem Records",
  description: "Generated by create next app",
};


export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {

  return (
    <html lang="pt-br" className={`${interFont.className}`} suppressHydrationWarning>
      <body>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          <CartProvider>
            <SearchHistoryProvider>
              <FavoritesProvider>
                <HeaderLogo/>
                {children}
                <SpeedInsights />
                <Navbar/>
              </FavoritesProvider>
            </SearchHistoryProvider>
          </CartProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
