import type { Metadata } from "next";
import { Inter, Libre_Caslon_Text } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "../components/theme-provider";
import Image from 'next/image';
import Link from "next/link";

const interFont = Inter({
  subsets: ["latin"]
})

const libreFont = Libre_Caslon_Text({
  weight: "400"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="pt-br" className={interFont.className} suppressHydrationWarning>
      <body>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          <nav className={`${libreFont.className} flex items-center justify-center gap-2 h-16 border-b-1 border-b-neutral-700`} style={{ backgroundColor: '#0D0D0D' }}>
              <Image src="logo.svg" alt="Logo Disco de Vinil" width={34} height={34}/>
              <h1 className="text-white text-lg">MAYHEM RECORDS</h1>
            </nav>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
